# Generated by Django 4.1.7 on 2023-03-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
