# Generated by Django 4.1.7 on 2023-03-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.CharField(max_length=2000),
        ),
    ]
