# Generated by Django 4.1.7 on 2023-03-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages', '0002_alter_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
